### PR TITLE
Add Couchpotato as an enhanced app

### PR DESCRIPTION
**Pull request by albertsj1**
heimdall_couchpotato

@KodeStar For this one, I added a config checkbox for 'aggressive polling' which uses the active/inactive feature that was recently added to Heimdall.  It allows the user to decide how often they want to query CouchPotato.  I set the default to poll less aggressively (aka 'inactive').  I think for this particular app, polling every 20 seconds or so is sufficient feedback for the user.

### CODE REVIEW

**Comment by KodeStar** [comment]
I don't get it?  What does aggressive_polling do?  It doesn't appear to be referenced anywhere? Did you miss some files out?  

There is already a mechanism in place for only querying every 20 seconds, you just add <input type="hidden" data-config="dataonly" class="config-item" name="config[dataonly]" value="1" /> to the blade.

Lastly that icon is crap, lol.

**Comment by albertsj1** [comment]
The aggressive polling toggle is just a way for the user to choose polling every 20 seconds or every second via the new active/inactive feature you added that is returned from the executeConfig function.
If you're not happy with exposing this feature as a user config option, I can remove it.  I added it because I personally don't want to poll my CouchPotato server every second.
Yeah, sorry about the icon.  The icon of a couch is too long and doesn't look right at this size, so I decided to use the favicon used for the server and scaled it to the right size.
I just created a new icon using the same font as the favicon and made the background transparent.

**Comment by albertsj1** [comment]
@KodeStar Please let me know if there is anything else you'd like me to change in this PR.

**Comment by KodeStar** [comment]
I'm still not 100% sure about the aggressive polling, I can't think of a single situation where you would *want* it to poll every second, it's not like nzbget where you can see the dl speed and amount remaining. I don't know why you wouldn't just set it to poll every 20 seconds.

**Comment by albertsj1** [comment]
yep. I agree.  I've just removed the aggressive polling option and associated language file changes.

**Comment by albertsj1** [comment]
This is how it looks with the updated icon.

couch_new

**Pull request merged**
