### PR TITLE
added autofocus to search input #149

### PR DESCRIPTION
**Pull request by kimpenhaus**

### CODE REVIEW

**Comment by KodeStar** [comment]
The image is too small and the quality is a little low.  The rest looks great.  It would be better if this was 2 PR's because I would have approved the Search thing independently

**Comment by kimpenhaus** [comment]
Strange, I made the pull request before adding Headphones as supported app. Maybe I messed something up. Need to b double check. Sorry

**Comment by kimpenhaus** [comment]
@KodeStar - I changed the pull request as it was to have just the changes on the autofocus. Please review again and sorry for the chaos :-)

Cheers

**Comment by KodeStar** [comment]
No problem, thanks for taking the time to create PRs

**Pull request merged**
