### PR TITLE
Foundation App: LibreNMS

### PR DESCRIPTION
**Pull request by ullbergm**
Name: LibreNMS
URL: https://www.librenms.org/
License: GNU General Public License v3.0
Summary: Community-based GPL-licensed network monitoring system 
Icon Source: [Here](https://idroot.net/wp-content/uploads/2018/01/LibreNSM-logo.png)

### CODE REVIEW

**Comment by MindTooth** [comment]
Is the LazyLibrarion commits part of this PR, or the other one you've submitted? Just wanted to let you know. 🍺

**Comment by ullbergm** [comment]
oops, my bad. i'll fix it.

**Comment by ullbergm** [comment]
All better now. 

I guess I was doing too many things at once. :)

**Comment by MindTooth** [comment]
Don't we all 😆

**Pull request merged**
