### PR TITLE
feat: add chinese lang support

### PR DESCRIPTION
**Pull request by dengshenkk**

### CODE REVIEW

**Comment by renweibo** [comment]
The translation seems good, please merge it for chinese users, thanks.

**Comment by xiazeyu** [comment]
LGTM

**Comment by dengshenkk** [comment]
看官方怎么说吧~

**Comment by hjkl950217** [comment]
官方似乎没有维护了样，2年多了没人推过代码。。我进大佬的仓库把zh文件夹拉下来映射到de上面就好了。。 感谢大佬 @dengshenkk

**Comment by KodeStar** [comment]
Merged into #794 feel free to add your comments tot hat one though

**Pull request closed without merging**
