### PR TITLE
feat: added ruTorrent to supported Apps - Closes #35

### LINKED ISSUE #35: SupportedApp - Rtorrent/Rutorrent

### PR DESCRIPTION
**Pull request by cheesemarathon**

### CODE REVIEW

**Comment by KodeStar** [comment]
That logo is utter crap.  If a better one can't be found then I might have to recreate it from scratch.

**Comment by cheesemarathon** [comment]
Is [this](https://imgur.com/a/KQI5P) any better? Or does it need to be closer to the original? Would result in something like [this](https://i.imgur.com/eEO6UjA.png). The original is the simplest looking ruTorrent logo I could find. The others I could find are small variations on that but pretty much exactly the same.

**Comment by KodeStar** [comment]
Looks better to me, I'm not that fussy, if others want a closer to the original image they can send a pull request, make the change and I'll approve, thanks

**Comment by cheesemarathon** [comment]
@KodeStar Done

**Pull request merged**
