### PR TITLE
Tautulli support

### PR DESCRIPTION
**Pull request by CHBMB**
Plexpy has been renamed/revamped to Tautulli, I haven't removed Plexpy as some people may still be using it.

### CODE REVIEW

**Comment by KodeStar** [comment]
This is missing being added to the Item.php, the readme also hasn't been updated

**Comment by CHBMB** [comment]
My bad.....

**Comment by halorrr** [comment]
Added all the needed files in #141

**Comment by CHBMB** [comment]
@halorrr Thanks, had only just got around to coming back to this.  I'll close this PR then.

**Pull request closed without merging**
