### PR TITLE
Update FormBuilder.php

### PR DESCRIPTION
**Pull request by shaohao**
Make she the value is passed to password input.

### CODE REVIEW

**Comment by farnots** [comment]
Working great thanks :+1:

**Comment by KrunchMuffin** [comment]
can we get this merged?

**Comment by shaohao** [comment]
> can we get this merged?

I have submiited a pull request.

**Comment by farnots** [comment]
> > can we get this merged?
> 
> I have submiited a pull request.

This is already a pull request ...

**Comment by shaohao** [comment]
> > > can we get this merged?
> > 
> > 
> > I have submiited a pull request.
> 
> This is already a pull request ...

Yeah, haha...
Call the repo owner merging this. I do not have write access

**Comment by KodeStar** [comment]
This is a 3rd party dependency and would need to be changed upstream - https://github.com/LaravelCollective/html/blob/6.x/src/FormBuilder.php#L334

**Comment by KrunchMuffin** [comment]
Ahh...ok. I changed it anyway.

**Comment by idolize** [comment]
Can this be merged in the meantime since many people are still using v2?

**Comment by adripo** [comment]
@KodeStar any news about this pull request?
When will come out v3?

**Pull request merged**
